name: build-windows-exe

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/packaging/requirements-lite.txt pyinstaller
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --clean ^
            --onefile --windowed ^
            --name ClassOnFace ^
            --add-data "scripts/webui/static;webui/static" ^
            scripts/web_ui.py
      - name: Package artifact
        run: |
          mkdir upload
          copy dist\ClassOnFace.exe upload\ClassOnFace.exe
          rem Include a simple run script and README
          echo start "ClassOnFace" /b ClassOnFace.exe > upload\run.bat
          echo Open http://127.0.0.1:8000/ in your browser. >> upload\README.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ClassOnFace-windows-exe
          path: upload

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ClassOnFace-windows-exe
          path: upload
      - name: Create Zip
        run: |
          cd upload
          zip -r ClassOnFace-windows.zip .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/ClassOnFace-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
